export const FETCH_ALL_COUNTRIES_REQUEST = 'FETCH_ALL_COUNTRIES_REQUEST';
export const FETCH_ALL_COUNTRIES_SUCCESS = 'FETCH_ALL_COUNTRIES_SUCCESS';
export const FETCH_ALL_COUNTRIES_FAILURE = 'FETCH_ALL_COUNTRIES_REFAILURE';

export const FILTER_COUNTRIES_BY_REGION_REQUEST = 'FILTER_COUNTRIES_BY_REGION_REQUEST';
export const FILTER_COUNTRIES_BY_REGION_SUCCESS = 'FILTER_COUNTRIES_BY_REGION_SUCCESS';
export const FILTER_COUNTRIES_BY_REGION_FAILURE = 'FILTER_COUNTRIES_BY_SEARCH_FAILURE';

export const FILTER_COUNTRIES_BY_SEARCH_REQUEST = 'FILTER_COUNTRIES_BY_SEARCH_REQUEST';
export const FILTER_COUNTRIES_BY_SEARCH_SUCCESS = 'FILTER_COUNTRIES_BY_SEARCH_SUCCESS';
export const FILTER_COUNTRIES_BY_SEARCH_FAILURE = 'FILTER_COUNTRIES_BY_SEARCH_FAILURE';

export const CHANGE_THEME = 'CHANGE_THEME';
export const NAVBAR_REDIRECT = 'NAVBAR_REDIRECT';
